# CBCS ----

cbcs.locations <- data.frame(Dept.Name = c("Aptive Environmental, LLC; Aptive Environmental Inc",
                                           "DUNEDIN - SALES",
                                           "LAKELAND - DIST",
                                           "LAKELAND - SALES",
                                           "SARASOTA - DIST",
                                           "SARASOTA - ES",
                                           "SARASOTA - SALES",
                                           "SPRING HILL - DIST",
                                           "SPRING HILL - SALES",
                                           "TAMPA CABOT WAREHOUSE - SALES",
                                           "TAMPA DC",
                                           "TAMPA DC - DIST",
                                           "TAMPA DC - ES",
                                           "TAMPA DC - SALES",
                                           "TAMPA PC",
                                           "TAMPA PC - DIST",
                                           "TAMPA PC - ES",
                                           "TAMPA PC - FLEET",
                                           "TAMPA PC - PROD",
                                           "TAMPA PC - SALES",
                                           "BROWARD",
                                           "BROWARD - DIST",
                                           "BROWARD - ES",
                                           "BROWARD - FLEET",
                                           "BROWARD - PROD",
                                           "BROWARD - SALES",
                                           "FT. MYERS - DIST",
                                           "FT. MYERS - ES",
                                           "FT. MYERS - FLEET",
                                           "FT. MYERS - SALES",
                                           "SENECA WAREHOUSE - DIST",
                                           "GAINESVILLE - DIST",
                                           "GAINESVILLE - SALES",
                                           "JACKSONVILLE - DIST",
                                           "JACKSONVILLE - ES",
                                           "JACKSONVILLE - FLEET",
                                           "JACKSONVILLE - PROD",
                                           "JACKSONVILLE - SALES",
                                           "JACKSONVILLE H2 - DIST",
                                           "JACKSONVILLE H2 - FLEET",
                                           "JACKSONVILLE H2 - PROD",
                                           "OCALA - SALES",
                                           "BREVARD (COCOA) - DIST",
                                           "BREVARD (COCOA) - ES",
                                           "BREVARD (COCOA) - FLEET",
                                           "BREVARD (COCOA) - SALES",
                                           "DAYTONA",
                                           "DAYTONA - DIST",
                                           "DAYTONA - ES",
                                           "DAYTONA - FLEET",
                                           "DAYTONA - SALES",
                                           "ORLANDO",
                                           "ORLANDO - DIST",
                                           "ORLANDO - ES",
                                           "ORLANDO - FLEET",
                                           "ORLANDO - PROD",
                                           "ORLANDO - SALES",
                                           "ORLANDO MRC - DIST",
                                           "ORLANDO MRC - ES",
                                           "WILDWOOD - DIST",
                                           "FT. PIERCE - DIST",
                                           "FT. PIERCE - ES",
                                           "FT. PIERCE - FLEET",
                                           "FT. PIERCE - SALES",
                                           "MIAMI DADE - DIST",
                                           "MIAMI DADE - ES",
                                           "MIAMI DADE - FLEET",
                                           "MIAMI DADE - SALES",
                                           "PALM BEACH - DIST",
                                           "PALM BEACH - ES",
                                           "PALM BEACH - FLEET",
                                           "PALM BEACH - SALES",
                                           "THE KEYS - DIST",
                                           "THE KEYS - ES",
                                           "THE KEYS - FLEET",
                                           "THE KEYS - SALES",
                                           "Coca-Cola Beverages Florida LLC",
                                           "HEADQUARTERS",
                                           "HEADQUARTERS - HQ"
),		
manager = c("PLACEHOLDER",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "FT MYERS - BROWARD",
            "FT MYERS - BROWARD",
            "FT MYERS - BROWARD",
            "FT MYERS - BROWARD",
            "FT MYERS - BROWARD",
            "FT MYERS - BROWARD",
            "FT MYERS - BROWARD",
            "FT MYERS - BROWARD",
            "FT MYERS - BROWARD",
            "FT MYERS - BROWARD",
            "FT MYERS - BROWARD",
            "JACKSONVILLE",
            "JACKSONVILLE",
            "JACKSONVILLE",
            "JACKSONVILLE",
            "JACKSONVILLE",
            "JACKSONVILLE",
            "JACKSONVILLE",
            "JACKSONVILLE",
            "JACKSONVILLE",
            "JACKSONVILLE",
            "JACKSONVILLE",
            "ORLANDO",
            "ORLANDO",
            "ORLANDO",
            "ORLANDO",
            "ORLANDO",
            "ORLANDO",
            "ORLANDO",
            "ORLANDO",
            "ORLANDO",
            "ORLANDO",
            "ORLANDO",
            "ORLANDO",
            "ORLANDO",
            "ORLANDO",
            "ORLANDO",
            "ORLANDO",
            "ORLANDO",
            "ORLANDO",
            "SOUTH FL",
            "SOUTH FL",
            "SOUTH FL",
            "SOUTH FL",
            "SOUTH FL",
            "SOUTH FL",
            "SOUTH FL",
            "SOUTH FL",
            "SOUTH FL",
            "SOUTH FL",
            "SOUTH FL",
            "SOUTH FL",
            "SOUTH FL",
            "SOUTH FL",
            "SOUTH FL",
            "SOUTH FL",
            "PLACEHOLDER",
            "PLACEHOLDER",
            "PLACEHOLDER")
)

cbcs.locations$Dept.Name <- as.character(cbcs.locations$Dept.Name)

# JJ Keller ----

jjkeller.locations <- data.frame(Assigned.Location = c("Lakeland FL",
                                                       "Tampa Fleet Shop Non-DOT",
                                                       "Tampa DC Non-DOT",
                                                       "Lakeland FL Non-DOT",
                                                       "Tampa DC",
                                                       "Tampa Transportation",
                                                       "Tampa Fleet Shop",
                                                       "Tampa Equipment Services",
                                                       "Tampa Transportation Non-DOT",
                                                       "Tampa Equipment Services Non-DOT",
                                                       "Sarasota FL Non-DOT",
                                                       "Sarasota FL",
                                                       "Tampa HQ Non-DOT",
                                                       "Coca-Cola Beverages Florida, LLC",
                                                       "Broward FL Non-DOT",
                                                       "Broward FL",
                                                       "Fort Myers FL",
                                                       "Fort Myers FL Non-DOT",
                                                       "Jacksonville FL Non-DOT",
                                                       "Jacksonville FL",
                                                       "Gainesville FL Non-DOT",
                                                       "Gainesville FL",
                                                       "Orlando FL",
                                                       "Orlando FL Non-DOT",
                                                       "N Florida Cust Care (Orlando Equipment Svcs)",
                                                       "Daytona FL",
                                                       "Brevard FL Non-DOT (Cocoa)",
                                                       "Brevard FL (Cocoa)",
                                                       "Orlando MRC Non-DOT",
                                                       "Daytona FL Non-DOT",
                                                       "Orlando Transportation",
                                                       "Orlando Transportation Non DOT",
                                                       "Orlando MRC",
                                                       "N Florida Cust Care (Orlando Equipment Svcs) Non D",
                                                       "Miami Dade FL",
                                                       "Palm Beach FL",
                                                       "Fort Pierce FL",
                                                       "Miami Dade FL Non-DOT",
                                                       "Palm Beach FL Non-DOT",
                                                       "S Florida Cust Care",
                                                       "Fort Pierce FL Non-DOT",
                                                       "The Keys FL",
                                                       "The Keys FL Non-DOT",
                                                       "S Florida Cust Care Non- DOT",
                                                       "Pre-Employment Non-DOT",
                                                       "Pre-Employment DOT"
),		
manager = c("TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "FT MYERS - BROWARD",
            "FT MYERS - BROWARD",
            "FT MYERS - BROWARD",
            "FT MYERS - BROWARD",
            "JACKSONVILLE",
            "JACKSONVILLE",
            "JACKSONVILLE",
            "JACKSONVILLE",
            "ORLANDO",
            "ORLANDO",
            "ORLANDO",
            "ORLANDO",
            "ORLANDO",
            "ORLANDO",
            "ORLANDO",
            "ORLANDO",
            "ORLANDO",
            "ORLANDO",
            "ORLANDO",
            "ORLANDO",
            "SOUTH FL",
            "SOUTH FL",
            "SOUTH FL",
            "SOUTH FL",
            "SOUTH FL",
            "SOUTH FL",
            "SOUTH FL",
            "SOUTH FL",
            "SOUTH FL",
            "SOUTH FL",
            "PLACEHOLDER",
            "PLACEHOLDER")
)

# LMS ----

lms.locations <- data.frame(
  manager = c(
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    # "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "TAMPA",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "FT MYERS - BROWARD",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "ORLANDO",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE",
    "JACKSONVILLE"
    
  ),
  
  location = c(
    "Tampa Fleet",
    "Tampa Fleet",
    "Tampa Fleet",
    "Tampa Fleet",
    "Lakeland",
    "Lakeland",
    "Lakeland",
    "Lakeland",
    "Lakeland",
    "Lakeland",
    "Lakeland",
    "Lakeland",
    "Lakeland",
    "Lakeland",
    "Lakeland",
    "Lakeland",
    "Lakeland",
    "Lakeland",
    "Lakeland",
    "Lakeland",
    "Lakeland",
    "Sarasota",
    "Sarasota",
    "Sarasota",
    "Sarasota",
    "Sarasota",
    "Sarasota",
    # "Sarasota",
    "Sarasota",
    "Sarasota",
    "Sarasota",
    "Sarasota",
    "Sarasota",
    "Sarasota",
    "Sarasota",
    "Sarasota",
    "Sarasota",
    "Sarasota",
    "Sarasota",
    "Sarasota",
    "Sarasota",
    "Spring Hill",
    "Spring Hill",
    "Spring Hill",
    "Spring Hill",
    "Spring Hill",
    "Spring Hill",
    "Spring Hill",
    "Spring Hill",
    "St Petersburg",
    "St Petersburg",
    "St Petersburg",
    "St Petersburg",
    "St Petersburg",
    "St Petersburg",
    "St Petersburg",
    "St Petersburg",
    "St Petersburg",
    "St Petersburg",
    "St Petersburg",
    "Tampa DC",
    "Tampa DC",
    "Tampa DC",
    "Tampa DC",
    "Tampa DC",
    "Tampa DC",
    "Tampa DC",
    "Tampa DC",
    "Tampa DC",
    "Tampa DC",
    "Tampa DC",
    "Tampa DC",
    "Tampa DC",
    "Tampa DC",
    "Tampa DC",
    "Tampa DC",
    "Tampa DC",
    "Tampa DC",
    "Tampa DC",
    "Tampa DC",
    "Tampa DC",
    "Tampa DC",
    "Tampa DC",
    "Tampa DC",
    "Tampa DC",
    "Tampa DC",
    "Tampa DC",
    "Tampa DC",
    "Tampa DC",
    "Tampa DC",
    "Tampa DC",
    "Tampa DC",
    "Tampa DC",
    "Tampa DC",
    "Tampa DC",
    "Tampa DC",
    "Tampa ES",
    "Tampa ES",
    "Tampa ES",
    "Tampa ES",
    "Tampa ES",
    "Tampa PC",
    "Tampa PC",
    "Tampa PC",
    "Tampa PC",
    "Tampa PC",
    "Tampa PC",
    "Tampa PC",
    "Tampa PC",
    "Tampa PC",
    "Tampa PC",
    "Tampa PC",
    "Tampa PC",
    "Tampa PC",
    "Tampa PC",
    "Tampa PC",
    "Tampa PC",
    "Tampa PC",
    "Tampa Transport",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Ft. Myers",
    "Ft. Myers",
    "Ft. Myers",
    "Ft. Myers",
    "Ft. Myers",
    "Ft. Myers",
    "Ft. Myers",
    "Ft. Myers",
    "Ft. Myers",
    "Ft. Myers",
    "Ft. Myers",
    "Ft. Myers",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Ft. Myers",
    "Ft. Myers",
    "Ft. Myers",
    "Ft. Myers",
    "Ft. Myers",
    "Ft. Myers",
    "Ft. Myers",
    "Ft. Myers",
    "Ft. Myers",
    "Ft. Myers",
    "Ft. Myers",
    "Ft. Myers",
    "Ft. Myers",
    "Ft. Myers",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Brevard",
    "Brevard",
    "Field Service",
    "Field Service",
    "Brevard",
    "Brevard",
    "Brevard",
    "Brevard",
    "Brevard",
    "Brevard",
    "Brevard",
    "Brevard",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Daytona",
    "Daytona",
    "Daytona",
    "Daytona",
    "Daytona",
    "Daytona",
    "Daytona",
    "Daytona",
    "Daytona",
    "Daytona",
    "Daytona",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Daytona",
    "Field Service",
    "Field Service",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Field Service",
    "Field Service",
    "Field Service",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Gainesville",
    "Gainesville",
    "Gainesville",
    "Gainesville",
    "Gainesville",
    "Gainesville",
    "Gainesville",
    "Gainesville",
    "Gainesville",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Gainesville",
    "Ocala ",
    "Ocala ",
    "Ocala ",
    "Ocala ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville ",
    "Jacksonville "
    
  ),
  
  Org.Name = c(
    "Fleet",
    "Lakeland Fleet",
    "Tampa/Lakeland/Ft Pierce Fleet",
    "Tampa/Sarasota/Ft Myers Fleet",
    "Lakeland Distribution 1",
    "Lakeland Distribution 2",
    "Lakeland Distribution 3",
    "Lakeland Sales Team 1",
    "Lakeland Sales Team 2",
    "Lakeland Sales Team 3",
    "Lakeland Sales Merchandising Team 1",
    "Lakeland Sales Merchandising Team 2",
    "Lakeland Sales Merchandising Team 3",
    "Lakeland Sales Merchandising Team 4",
    "Lakeland Sales Merchandising Team 5",
    "Lakeland Warehouse 1",
    "Lakeland Warehouse 2",
    "Lakeland Warehouse 3",
    "Lakeland Territory",
    "Lakeland Logistics",
    "Lakeland Sales",
    "Sarasota Distribution 1",
    "Sarasota Distribution 2",
    "Sarasota Administration",
    "Sarasota Equipment Services",
    "Sarasota Logistics",
    "Sarasota Full Service",
    "Sarasota Sales Merchandising Team 1",
    "Sarasota Sales Merchandising Team 2",
    "Sarasota Sales Merchandising Team 3",
    "Sarasota Sales Merchandising Team 4",
    "Sarasota Sales Merchandising Team 5",
    "Sarasota Merchandising 1",
    "Sarasota Sales",
    "Sarasota Sales Team 1",
    "Sarasota Sales Team 2",
    # "Sarasota Sales Team 3",
    "Sarasota Sales Team 4",
    "Sarasota Territory",
    "Sarasota Warehouse 1",
    "Sarasota Warehouse 2",
    "Springhill Distribution",
    "Spring Hill Sales Merchandising Team 1",
    "Spring Hill Sales Merchandising Team 2",
    "Spring Hill Sales Merchandising Team 3",
    "Spring Hill Sales Merchandising Team 4",
    "Spring Hill Sales Team 1",
    "Spring Hill Sales Team 2",
    "Spring Hill Territory",
    "St Petersburg Sales Merchandising Team 1",
    "St Petersburg Sales Merchandising Team 2",
    "St Petersburg Sales Merchandising Team 3",
    "St Petersburg Sales Merchandising Team 4",
    "St Petersburg Sales Merchandising Team 5",
    "St Petersburg Sales Merchandising Team 6",
    "St Petersburg Sales",
    "St Petersburg Sales Team 1",
    "St Petersburg Sales Team 2",
    "St Petersburg Sales Team 3",
    "St Petersburg Sales Team 4",
    "Reset Sales Team 4",
    "Tampa Distribution",
    "Tampa Distribution 1",
    "Tampa Distribution 2",
    "Tampa Distribution 3",
    "Tampa Distribution 4",
    "Tampa Distribution 5",
    "Tampa Distribution 6",
    "Tampa Full Service 1",
    "Tampa Full Service 2",
    "Tampa Inventory",
    "Tampa Logistics",
    "Tampa Sales",
    "Tampa Sales 1",
    "Tampa Sales 2",
    "Tampa Sales 3",
    "Tampa Sales 4",
    "Tampa Sales 5",
    "Tampa Sales Merchandising 1",
    "Tampa Sales Merchandising 2",
    "Tampa Sales Merchandising 3",
    "Tampa Sales Merchandising 4",
    "Tampa Sales Merchandising 5",
    "Tampa Sales Merchandising 6",
    "Tampa Sales Merchandising 7",
    "Tampa Sales Team",
    "Tampa Territory",
    "Tampa Warehouse",
    "Tampa Warehouse 1",
    "Tampa Warehouse 2",
    "Tampa Warehouse 3",
    "Tampa Warehouse 4",
    "Tampa Warehouse 5",
    "Tampa Warehouse 6",
    "Tampa Warehouse 7",
    "Tampa Warehouse 8",
    "Tampa Equipment Svc Planned Bottle/Can",
    "Tampa Equipment Svc Planned Fountain",
    "Equipment Services",
    "Tampa Equipment Services 1",
    "Tampa Equipment Services 2",
    "Tampa Production Team 1",
    "Tampa Production Team 2",
    "Tampa Production Team 3",
    "Tampa Production Team 4",
    "Tampa Production Team 5",
    "Tampa Production Team 6",
    "Tampa Warehouse Team 1",
    "Tampa Warehouse Team 2",
    "Tampa Warehouse Team 3",
    "Tampa Maintenance Team 1",
    "Tampa Maintenance Team 2",
    "Tampa Maintenance",
    "Tampa Production Center",
    "Tampa Inventory Control",
    "Tampa Operations",
    "Tampa Quality Assurance",
    "Tampa Quality Assurance Team",
    "Florida Private Fleet",
    "Hollywood Warehouse Team 8",	
    "Hollywood Warehouse Team 8",	
    "Hollywood Warehouse Team 3",	
    "Hollywood Warehouse Team 9",	
    "Hollywood Warehouse Team 5",	
    "Hollywood Warehouse Team 2",	
    "Broward Sales Merchandising Team 13",	
    "Broward Sales Merchandising Team 4",	
    "Hollywood Warehouse Team 6",	
    "Hollywood Warehouse Team 1A",	
    "Broward Sales Merchandising Team 10",	
    "Hollywood Distribution Bulk Team 2",	
    "Hollywood Production 9",	
    "Hollywood Production 4",	
    "Hollywood Distribution",	
    "Commercial Operations - South",	
    "Hollywood Distribution OFS Team 3",	
    "Hollywood Distribution Bulk Team 3",	
    "Talent and Learning",	
    "Hollywood Distribution OFS Team 2",	
    "Broward Sales Merchandising Team 7",	
    "Management Systems Team - Hollywood FL",	
    "Broward Territory",	
    "Broward Sales Merchandising Team 5",	
    "Hollywood Production 6",	
    "Hollywood Distribution OFS Team 4",	
    "Hollywood Distribution OFS Team 1",	
    "Hollywood Production 7",	
    "Hollywood Production 3",	
    "Hollywood Maintenance Team 3",	
    "Broward Inventory",	
    "Broward Sales 7",	
    "Broward Sales",	
    "Broward Sales Merchandising Team 2",	
    "Broward Sales Merchandising Team 9",	
    "Hollywood Equipment Services Team I",	
    "Hollywood Equipment Service Team III",	
    "Finance Services Team 1",	
    "Hollywood Production 1",	
    "Hollywood Production Sanitation",	
    "Broward Inventory Team 1",	
    "Hollywood Cooler Mover Team",	
    "Broward Sales Merchandising Team 1",	
    "Hollywood Production 8",	
    "Hollywood Quality Control Team 3",	
    "Florida Division Fleet - Hollywood",	
    "Broward Sales Merchandising Team 11",	
    "Hollywood Warehouse Team 3A",	
    "Hollywood Warehouse Team 6A",	
    "Hollywood Equipment Services Team 2",	
    "Hollywood Warehouse Team 2A",	
    "Hollywood Production 10",	
    "Broward Sales Merchandising Team 12",	
    "Broward Business Development Team",	
    "Broward Sales 1",	
    "Broward Sales Merchandising Team 8",	
    "Broward Sales Team 1",	
    "Broward Sales 4",	
    "Broward Sales 8",	
    "Broward Sales 5",	
    "Reset Sales Team 3",	
    "Environmental Health Safety & Sustain",	
    "Broward Sales Merchandising Team 3",	
    "Hollywood Maintenance Team 1",	
    "Broward Logistics",	
    "Hollywood Distribution OFS Team 5",	
    "Broward Sales Merchandising Team 6",	
    "Broward Sales 3",	
    "Hollywood Full Service",	
    "Hollywood Warehouse Team 4",	
    "Hollywood Quality Control Team 2",	
    "Small Store Customer Management",	
    "Hollywood Distribution Bulk Team 1",	
    "Hollywood Quality Control Team 1",	
    "Hollywood Warehouse Team 4A",	
    "Hollywood Maintenance Team 4",	
    "US Region Field Ops - Field Svc MU Lead",	
    "Hollywood Production",	
    "Finance Services Team 3",	
    "Hollywood Warehouse Team 1",	
    "Hollywood Warehouse Team 7",	
    "Hollywood Maintenance",	
    "Broward Sales 2",	
    "Broward Sales Team 2",	
    "Regional and Local Accounts Customer Mgt",	
    "Security",	
    "Broward Warehouse Team",	
    "Director Field IT",	
    "FSOP Customer Management (South)",	
    "Hollywood Quality Assurance",	
    "Hollywood Production Center",	
    "Public Affairs and Community Relations",	
    "Hollywood Maintenance Team 2",	
    "Corporate HR & Ops",	
    "Hollywood Warehouse",	
    "Manager, Internal Control",	
    "Fort Myers Warehouse 2",	
    "Fort Myers Warehouse 1",	
    "Ft Myers Equipment Services",	
    "Fort Myers Territory",	
    "Fort Myers Logistics",	
    "Fort Myers Distribution 2",	
    "Fort Myers Distribution 1",	
    "Fort Myers Distribution 4",	
    "Fort Myers Distribution 3",	
    "Fort Myers Warehouse 3",	
    "Ft Myers Sales",	
    "Fort Myers Warehouse",
    "Broward Distribution",
    "Broward Distribution Team 1",
    "Broward Distribution Team 2",
    "Broward Distribution Team 3",
    "Broward Distribution Team 4",
    "Broward Distribution Team 5",
    "Broward Distribution Team 6",
    "Broward Distribution Team 7",
    "Broward Distribution Team 8",
    "Broward Distribution Team 9",
    "Broward Field Service Team 1",
    "Broward Field Service Team 2",
    "Broward Field Service Team 3",
    "Broward Maintenance",
    "Broward Maintenance Team 1",
    "Broward Maintenance Team 3",
    "Broward Maintenance Team 4",
    "Broward Management Systems Team",
    "Broward Production",
    "Broward Production 1",
    "Broward Production 10",
    "Broward Production 3",
    "Broward Production 4",
    "Broward Production 6",
    "Broward Production 7",
    "Broward Production 8",
    "Broward Production 9",
    "Broward Production Warehouse 1",
    "Broward Production Warehouse 2",
    "Broward Production Warehouse 3",
    "Broward Production Warehouse 4",
    "Broward Production Warehouse 6",
    "Broward Warehouse Team 1",
    "Broward Warehouse Team 2",
    "Broward/The Keys Fleet",
    "Field IT",
    "Field Service Team 3",
    "Internal Control",
    "Ft Myers Business Development Team",
    "Ft Myers Field Service",
    "Ft Myers Sales Merchandising Team 1",
    "Ft Myers Sales Merchandising Team 2",
    "Ft Myers Sales Merchandising Team 3",
    "Ft Myers Sales Merchandising Team 4",
    "Ft Myers Sales Merchandising Team 5",
    "Ft Myers Sales Merchandising Team 6",
    "Ft Myers Sales Merchandising Team 7",
    "Ft Myers Sales Merchandising Team 8",
    "Ft Myers Sales Team 1",
    "Ft Myers Sales Team 2",
    "Ft Myers Sales Team 3",
    "Ft Myers Sales Team 4",
    "Broward Quality Assurance",
    "Broward Quality Assurance 1",
    "Broward Quality Assurance 2",
    "Broward Quality Assurance 3",
    "Broward Warehouse 3",
    "Broward Warehouse 4",
    "Broward Warehouse 5",
    "Broward Warehouse 6",
    "Brevard Distribution Team 1",
    "Brevard Distribution Team 2",
    "Brevard Field Service",
    "Brevard Full Service",
    "Brevard Sales Merchandising Team 1",
    "Brevard Sales Merchandising Team 2",
    "Brevard Sales Merchandising Team 3",
    "Brevard Sales Merchandising Team 4",
    "Brevard Sales Team 1",
    "Brevard Sales Team 2",
    "Brevard Territory",
    "Business Services and Systems",
    "Channel Marketing",
    "Commercial Capabilities",
    "Corporate HR & Ops",
    "Customer Management ï¿½ FSOP",    # NOTE the weird one is here and right below
    "Customer Management ï¿½ Retail",
    "Daytona Distribution",
    "Daytona Distribution Team 1",
    "Daytona Distribution Team 2",
    "Daytona Sales Merchandising Team 1",
    "Daytona Sales Merchandising Team 2",
    "Daytona Sales Merchandising Team 3",
    "Daytona Sales Merchandising Team 4",
    "Daytona Sales Team 1",
    "Daytona Sales Team 2",
    "Daytona Sales Team 3",
    "Daytona Territory",
    "Environmental Health Safety & Sustain",
    "Field IT",
    "Finance Services Team 2",
    "Finance Services Team 3",
    "Jacksonville/Daytona Field Service Team",
    "Make Ready Center",
    "MRC & Field Service",
    "Ocala Sales Merchandising Team 4",
    "Orlando Business Development Team",
    "Orlando Distribution",
    "Orlando Distribution Center",
    "Orlando Distribution Team 1",
    "Orlando Distribution Team 2",
    "Orlando Distribution Team 3",
    "Orlando Distribution Team 4",
    "Orlando Distribution Team 5",
    "Orlando Distribution Team 6",
    "Orlando Distribution Team 7",
    "Orlando Field Service Team 1",
    "Orlando Field Service Team 2",
    "Orlando Field Service Team 3",
    "Orlando Full Service 1",
    "Orlando Full Service 2",
    "Orlando Inventory Control",
    "Orlando Maintenance",
    "Orlando Maintenance Team 1",
    "Orlando Maintenance Team 2",
    "Orlando Management Systems",
    "Orlando Manufacturing",
    "Orlando Production",
    "Orlando Production Team 1",
    "Orlando Production Team 2",
    "Orlando Production Team 3",
    "Orlando Production Team 4",
    "Orlando Production Team 5",
    "Orlando Production Team 6",
    "Orlando Quality Assurance",
    "Orlando Quality Assurance 1",
    "Orlando Quality Assurance 2",
    "Orlando Sales",
    "Orlando Sales 1",
    "Orlando Sales 10",
    "Orlando Sales 2",
    "Orlando Sales 3",
    "Orlando Sales 4",
    "Orlando Sales 5",
    "Orlando Sales 6",
    "Orlando Sales 7",
    "Orlando Sales 9",
    "Orlando Sales Merchandising Team 1",
    "Orlando Sales Merchandising Team 10",
    "Orlando Sales Merchandising Team 11",
    "Orlando Sales Merchandising Team 12",
    "Orlando Sales Merchandising Team 13",
    "Orlando Sales Merchandising Team 2",
    "Orlando Sales Merchandising Team 3",
    "Orlando Sales Merchandising Team 4",
    "Orlando Sales Merchandising Team 5",
    "Orlando Sales Merchandising Team 6",
    "Orlando Sales Merchandising Team 7",
    "Orlando Sales Merchandising Team 8",
    "Orlando Sales Merchandising Team 9",
    "Orlando Sales Team",
    "Orlando Territory",
    "Orlando Transport",
    "Orlando Warehouse Team 1",
    "Orlando Warehouse Team 10",
    "Orlando Warehouse Team 11",
    "Orlando Warehouse Team 2",
    "Orlando Warehouse Team 2A",
    "Orlando Warehouse Team 3",
    "Orlando Warehouse Team 3A",
    "Orlando Warehouse Team 4",
    "Orlando Warehouse Team 5",
    "Orlando Warehouse Team 6",
    "Orlando Warehouse Team 7",
    "Orlando Warehouse Team 8",
    "Orlando Warehouse Transportation",
    "Orlando/Brevard Fleet",
    "Reset Sales Team 1",
    "Reset Sales Team 2",
    "Talent and Learning",
    "Business Services and Systems",
    "Channel Marketing",
    "Corporate HR & Ops",
    "Engineering",
    "Environmental Health Safety & Sustain",
    "Field IT",
    "Field Service Team 2",
    "Finance Services Team 2",
    "FSOP Customer Management (South)",
    "Gainesville Distribution Team 1",
    "Gainesville Distribution Team 2",
    "Gainesville Distribution Team 3",
    "Gainesville Merchandising Team 1",
    "Gainesville Merchandising Team 2",
    "Gainesville Merchandising Team 3",
    "Gainesville Sales Team 1",
    "Gainesville Sales Team 2",
    "Gainesville Territory",
    "Jacksonville Business Development Team",
    "Jacksonville Distribution",
    "Jacksonville Distribution Team 1",
    "Jacksonville Distribution Team 2",
    "Jacksonville Distribution Team 3",
    "Jacksonville Distribution Team 4",
    "Jacksonville Distribution Team 5",
    "Jacksonville Field Service Team 1",
    "Jacksonville Full Service",
    "Jacksonville Inventory",
    "Jacksonville Inventory Team 1",
    "Jacksonville Inventory Team 2",
    "Jacksonville Inventory Team 3",
    "Jacksonville Logistics",
    "Jacksonville Maintenance",
    "Jacksonville Maintenance Team 1",
    "Jacksonville Maintenance Team 2",
    "Jacksonville Manufacturing",
    "Jacksonville Merchandising Team 1",
    "Jacksonville Merchandising Team 10",
    "Jacksonville Merchandising Team 2",
    "Jacksonville Merchandising Team 3",
    "Jacksonville Merchandising Team 4",
    "Jacksonville Merchandising Team 5",
    "Jacksonville Merchandising Team 6",
    "Jacksonville Merchandising Team 7",
    "Jacksonville Merchandising Team 8",
    "Jacksonville Merchandising Team 9",
    "Jacksonville Production",
    "Jacksonville Production Team 2",
    "Jacksonville Production Team 2",
    "Jacksonville Production Team 3",
    "Jacksonville Production Team 4",
    "Jacksonville Production Team 5",
    "Jacksonville Quality Assurance",
    "Jacksonville Quality Assurance Team 1",
    "Jacksonville Sales",
    "Jacksonville Sales 1",
    "Jacksonville Sales 2",
    "Jacksonville Sales 3",
    "Jacksonville Sales 5",
    "Jacksonville Sales 6",
    "Jacksonville Sales Team 1",
    "Jacksonville Sales Team 2",
    "Jacksonville Territory",
    "Jacksonville Transportation",
    "Jacksonville Warehouse Team 1",
    "Jacksonville Warehouse Team 2",
    "Jacksonville Warehouse Team 3",
    "Jacksonville Warehouse Team 4",
    "Jacksonville Warehouse Team 5",
    "Jacksonville Warehouse Team 6",
    "Jacksonville Warehouse Team 7",
    "Jacksonville/Daytona Field Service Team",
    "Jacksonville/Gainesville Fleet",
    "Jax/Gainesville Field Service Team",
    "Ocala Merchandising Team 3",
    "Ocala Sales Merchandising Team 1",
    "Ocala Sales Merchandising Team 4",
    "Ocala Territory",
    "Regional and Local Accounts Customer Mgt",
    "Reset Sales Team 2",
    "Security",
    "Talent and Learning",
    "Technology Solutions Team 1"
    
  )
)

lms.locations <- lms.locations %>% 
  mutate(Org.Name = recode(Org.Name,
                           "Customer Management Ã¯Â¿Â½ FSOP" = "Customer Management ï¿½ FSOP",
                           "Customer Management Ã¯Â¿Â½ Retail" = "Customer Management ï¿½ Retail"))

# STARS ----

stars.locations <- data.frame( Location = c("FT MYERS",
                                            "TAMPA DC",
                                            "ORLANDO COMBO CENTER",
                                            "HOLLYWOOD",
                                            "SARASOTA",
                                            "TAMPA (SABAL)",
                                            "SOUTH DADE",
                                            "DAYTONA DC",
                                            "JACKSONVILLE COMBO CENTER",
                                            "WEST PALM BEACH",
                                            "GAINESVILLE DC",
                                            "FORT PIERCE",
                                            "BIG PINE KEY",
                                            "BREVARD DC",
                                            "TAMPA HQ",
                                            "ORLANDO MRC",
                                            "LAKELAND",
                                            "COCA-COLA BEVERAGES FLORIDA, LLC",
                                            "JACKSONVILLE SURGE"),
                               manager = c("FT MYERS - BROWARD",
                                           "TAMPA",
                                           "ORLANDO",
                                           "FT MYERS - BROWARD",
                                           "TAMPA",
                                           "TAMPA",
                                           "SOUTH FL",
                                           "ORLANDO",
                                           "JACKSONVILLE",
                                           "SOUTH FL",
                                           "JACKSONVILLE",
                                           "SOUTH FL",
                                           "SOUTH FL",
                                           "ORLANDO",
                                           "PLACEHOLDER",
                                           "ORLANDO",
                                           "TAMPA",
                                           "PLACEHOLDER",
                                           "JACKSONVILLE")
                               )

stars.locations$Location <- as.character(stars.locations$Location)
