# CBCS ----

cbcs.locations <- data.frame(Dept.Name = c("Aptive Environmental, LLC; Aptive Environmental Inc",
                                           "GAINESVILLE - ES",
                                           "WINTER HAVEN - FLEET",
                                           "DUNEDIN - SALES",
                                           "WINTER HAVEN - DIST",
                                           "WINTER HAVEN - SALES",
                                           "SARASOTA - DIST",
                                           "SARASOTA - ES",
                                           "SARASOTA - SALES",
                                           "SPRING HILL - DIST",
                                           "SPRING HILL - SALES",
                                           "TAMPA CABOT WAREHOUSE - SALES",
                                           "TAMPA DC",
                                           "TAMPA DC - DIST",
                                           "TAMPA DC - ES",
                                           "TAMPA DC - SALES",
                                           "TAMPA PC",
                                           "TAMPA PC - DIST",
                                           "TAMPA PC - ES",
                                           "TAMPA PC - FLEET",
                                           "TAMPA PC - PROD",
                                           "TAMPA PC - SALES",
                                           "BROWARD",
                                           "BROWARD - DIST",
                                           "BROWARD - ES",
                                           "BROWARD - FLEET",
                                           "BROWARD - PROD",
                                           "BROWARD - SALES",
                                           "FT. MYERS - DIST",
                                           "FT. MYERS - ES",
                                           "FT. MYERS - FLEET",
                                           "FT. MYERS - SALES",
                                           "SENECA WAREHOUSE - DIST",
                                           "GAINESVILLE - DIST",
                                           "GAINESVILLE - SALES",
                                           "JACKSONVILLE - DIST",
                                           "JACKSONVILLE - ES",
                                           "JACKSONVILLE - FLEET",
                                           "JACKSONVILLE - PROD",
                                           "JACKSONVILLE - SALES",
                                           "JACKSONVILLE H2 - DIST",
                                           "JACKSONVILLE H2 - FLEET",
                                           "JACKSONVILLE H2 - PROD",
                                           "OCALA - SALES",
                                           "BREVARD (COCOA) - DIST",
                                           "BREVARD (COCOA) - ES",
                                           "BREVARD (COCOA) - FLEET",
                                           "BREVARD (COCOA) - SALES",
                                           "DAYTONA",
                                           "DAYTONA - DIST",
                                           "DAYTONA - ES",
                                           "DAYTONA - FLEET",
                                           "DAYTONA - SALES",
                                           "ORLANDO",
                                           "ORLANDO - DIST",
                                           "ORLANDO - ES",
                                           "ORLANDO - FLEET",
                                           "ORLANDO - PROD",
                                           "ORLANDO - SALES",
                                           "ORLANDO MRC - DIST",
                                           "ORLANDO MRC - ES",
                                           "WILDWOOD - DIST",
                                           "FT. PIERCE - DIST",
                                           "FT. PIERCE - ES",
                                           "FT. PIERCE - FLEET",
                                           "FT. PIERCE - SALES",
                                           "MIAMI DADE - DIST",
                                           "MIAMI DADE - ES",
                                           "MIAMI DADE - FLEET",
                                           "MIAMI DADE - SALES",
                                           "PALM BEACH - DIST",
                                           "PALM BEACH - ES",
                                           "PALM BEACH - FLEET",
                                           "PALM BEACH - SALES",
                                           "THE KEYS - DIST",
                                           "THE KEYS - ES",
                                           "THE KEYS - FLEET",
                                           "THE KEYS - SALES",
                                           "Coca-Cola Beverages Florida LLC",
                                           "HEADQUARTERS",
                                           "HEADQUARTERS - HQ",
                                           "SEBRING - DIST",
                                           "SEBRING - ES",
                                           "SEBRING - FLEET",
                                           "SEBRING - SALES",
                                           "GAINESVILLE - FLEET",
                                           "OCALA - DIST"
),
manager = c("PLACEHOLDER",
            "JACKSONVILLE",
            "ORLANDO",
            "TAMPA",
            "ORLANDO",
            "ORLANDO",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "BROWARD",
            "BROWARD",
            "BROWARD",
            "BROWARD",
            "BROWARD",
            "BROWARD",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "BROWARD",
            "JACKSONVILLE",
            "JACKSONVILLE",
            "JACKSONVILLE",
            "JACKSONVILLE",
            "JACKSONVILLE",
            "JACKSONVILLE",
            "JACKSONVILLE",
            "JACKSONVILLE",
            "JACKSONVILLE",
            "JACKSONVILLE",
            "JACKSONVILLE",
            "JACKSONVILLE",
            "JACKSONVILLE",
            "JACKSONVILLE",
            "JACKSONVILLE",
            "JACKSONVILLE",
            "JACKSONVILLE",
            "JACKSONVILLE",
            "JACKSONVILLE",
            "JACKSONVILLE",
            "ORLANDO",
            "ORLANDO",
            "ORLANDO",
            "ORLANDO",
            "ORLANDO",
            "ORLANDO",
            "ORLANDO",
            "ORLANDO",
            "ORLANDO",
            "ORLANDO",
            "ORLANDO",
            "ORLANDO",
            "ORLANDO",
            "BROWARD",
            "BROWARD",
            "BROWARD",
            "BROWARD",
            "BROWARD",
            "BROWARD",
            "BROWARD",
            "BROWARD",
            "BROWARD",
            "BROWARD",
            "BROWARD",
            "BROWARD",
            "PLACEHOLDER",
            "PLACEHOLDER",
            "PLACEHOLDER",
            "ORLANDO",
            "ORLANDO",
            "ORLANDO",
            "ORLANDO",
            "JACKSONVILLE",
            "JACKSONVILLE")
)

cbcs.locations$Dept.Name <- as.character(cbcs.locations$Dept.Name)

# JJ Keller ----

jjkeller.locations <- data.frame(Assigned.Location = c("Winter Haven FL",
                                                       "Tampa Fleet Shop Non-DOT",
                                                       "Tampa DC Non-DOT",
                                                       "Winter Haven FL Non-DOT",
                                                       "Tampa DC",
                                                       "Tampa Transportation",
                                                       "Tampa Fleet Shop",
                                                       "Tampa Equipment Services",
                                                       "Tampa Transportation Non-DOT",
                                                       "Tampa Equipment Services Non-DOT",
                                                       "Sarasota FL Non-DOT",
                                                       "Sarasota FL",
                                                       "Tampa HQ Non-DOT",
                                                       "Coca-Cola Beverages Florida, LLC",
                                                       "Broward FL Non-DOT",
                                                       "Broward FL",
                                                       "Fort Myers FL",
                                                       "Fort Myers FL Non-DOT",
                                                       "Jacksonville FL Non-DOT",
                                                       "Jacksonville FL",
                                                       "Gainesville FL Non-DOT",
                                                       "Gainesville FL",
                                                       "Orlando FL",
                                                       "Orlando FL Non-DOT",
                                                       "N Florida Cust Care (Orlando Equipment Svcs)",
                                                       "Daytona FL",
                                                       "Brevard FL Non-DOT (Cocoa)",
                                                       "Brevard FL (Cocoa)",
                                                       "Orlando MRC Non-DOT",
                                                       "Daytona FL Non-DOT",
                                                       "Orlando Transportation",
                                                       "Orlando Transportation Non DOT",
                                                       "Orlando MRC",
                                                       "N Florida Cust Care (Orlando Equipment Svcs) Non D",
                                                       "Miami Dade FL",
                                                       "Palm Beach FL",
                                                       "Fort Pierce FL",
                                                       "Miami Dade FL Non-DOT",
                                                       "Palm Beach FL Non-DOT",
                                                       "S Florida Cust Care",
                                                       "Fort Pierce FL Non-DOT",
                                                       "The Keys FL",
                                                       "The Keys FL Non-DOT",
                                                       "S Florida Cust Care Non- DOT",
                                                       "Pre-Employment Non-DOT",
                                                       "Pre-Employment DOT",
                                                       "Sebring FL",
                                                       "Sebring FL Non-DOT"
),
manager = c("ORLANDO",
            "TAMPA",
            "TAMPA",
            "ORLANDO",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "TAMPA",
            "BROWARD",
            "BROWARD",
            "TAMPA",
            "TAMPA",
            "JACKSONVILLE",
            "JACKSONVILLE",
            "JACKSONVILLE",
            "JACKSONVILLE",
            "ORLANDO",
            "ORLANDO",
            "ORLANDO",
            "JACKSONVILLE",
            "JACKSONVILLE",
            "JACKSONVILLE",
            "ORLANDO",
            "JACKSONVILLE",
            "ORLANDO",
            "ORLANDO",
            "ORLANDO",
            "ORLANDO",
            "BROWARD",
            "BROWARD",
            "ORLANDO",
            "BROWARD",
            "BROWARD",
            "BROWARD",
            "BROWARD",
            "BROWARD",
            "BROWARD",
            "BROWARD",
            "PLACEHOLDER",
            "PLACEHOLDER",
            "ORLANDO",
            "ORLANDO")
)

# LMS ----

library(tidyverse)

lms.locations <- readRDS("lms_fac_name.Rds") %>%
  mutate(manager = recode(manager,
         "BILL" = "TAMPA",
         "ANDREA" = "BROWARD",
         "JOHN" = "ORLANDO",
         "HUNTER" = "JACKSONVILLE"))

lms.locations$`Facility Name Link` <- lms.locations$Facility.Name

lms.locations$`Facility Name` <- str_remove(lms.locations$Facility.Name, "Center")
lms.locations$`Facility Name` <- str_remove(lms.locations$`Facility Name`, "Distribution")


lms.locations[15,]$manager <- "JACKSONVILLE"

# lms.locations <- data.frame(
#   manager = c(
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "JACKSONVILLE",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "ORLANDO",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "ORLANDO",
#     "ORLANDO",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "TAMPA",
#     "JACKSONVILLE",
#     "FT MYERS - BROWARD",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "FT MYERS - BROWARD",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "ORLANDO",
#     "ORLANDO",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "TAMPA",
#     "TAMPA",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "SOUTH FL",
#     "PLACEHOLDER"
#
#
#   ),
#
#   location = c(
#     "Tampa Fleet",
#     "Tampa Fleet",
#     "Tampa Fleet",
#     "Tampa Fleet",
#     "Winter Haven DIST",
#     "Winter Haven DIST",
#     "Winter Haven DIST",
#     "Winter Haven Sales",
#     "Winter Haven Sales",
#     "Winter Haven Sales",
#     "Winter Haven Sales",
#     "Winter Haven Sales",
#     "Winter Haven Sales",
#     "Winter Haven Sales",
#     "Winter Haven Sales",
#     "Winter Haven WHSE",
#     "Winter Haven WHSE",
#     "Winter Haven WHSE",
#     "Winter Haven Sales",
#     "Winter Haven Sales",
#     "Winter Haven Sales",
#     "Sarasota DIST",
#     "Sarasota DIST",
#     "Sarasota Sales",
#     "Sarasota ES",
#     "Sarasota Sales",
#     "Sarasota DIST",
#     "Sarasota Sales",
#     "Sarasota Sales",
#     "Sarasota Sales",
#     "Sarasota Sales",
#     "Sarasota Sales",
#     "Sarasota Sales",
#     "Sarasota Sales",
#     "Sarasota Sales",
#     "Sarasota Sales",
#     "Sarasota Sales",
#     "Sarasota Sales",
#     "Sarasota WHSE",
#     "Sarasota WHSE",
#     "Spring Hill DIST",
#     "Spring Hill Sales",
#     "Spring Hill Sales",
#     "Spring Hill Sales",
#     "Spring Hill Sales",
#     "Spring Hill Sales",
#     "Spring Hill Sales",
#     "Spring Hill Sales",
#     "St Petersburg Sales",
#     "St Petersburg Sales",
#     "St Petersburg Sales",
#     "St Petersburg Sales",
#     "St Petersburg Sales",
#     "St Petersburg Sales",
#     "St Petersburg Sales",
#     "St Petersburg Sales",
#     "St Petersburg Sales",
#     "St Petersburg Sales",
#     "St Petersburg Sales",
#     "Tampa DC Sales",
#     "Tampa DC DIST",
#     "Tampa DC DIST",
#     "Tampa DC DIST",
#     "Tampa DC DIST",
#     "Tampa DC DIST",
#     "Tampa DC DIST",
#     "Tampa DC DIST",
#     "Tampa DC DIST",
#     "Tampa DC DIST",
#     "Tampa DC WHSE",
#     "Tampa DC WHSE",
#     "Tampa DC Sales",
#     "Tampa DC Sales",
#     "Tampa DC Sales",
#     "Tampa DC Sales",
#     "Tampa DC Sales",
#     "Tampa DC Sales",
#     "Tampa DC Sales",
#     "Tampa DC Sales",
#     "Tampa DC Sales",
#     "Tampa DC Sales",
#     "Tampa DC Sales",
#     "Tampa DC Sales",
#     "Tampa DC Sales",
#     "Tampa DC Sales",
#     "Tampa DC Sales",
#     "Tampa DC WHSE",
#     "Tampa DC WHSE",
#     "Tampa DC WHSE",
#     "Tampa DC WHSE",
#     "Tampa DC WHSE",
#     "Tampa DC WHSE",
#     "Tampa DC WHSE",
#     "Tampa DC WHSE",
#     "Tampa DC WHSE",
#     "Tampa ES",
#     "Tampa ES",
#     "Tampa ES",
#     "Tampa ES",
#     "Tampa ES",
#     "Tampa PC Production",
#     "Tampa PC Production",
#     "Tampa PC Production",
#     "Tampa PC Production",
#     "Tampa PC Production",
#     "Tampa PC Production",
#     "Tampa PC WHSE",
#     "Tampa PC WHSE",
#     "Tampa PC WHSE",
#     "Tampa PC MAINT",
#     "Tampa PC MAINT",
#     "Tampa PC MAINT",
#     "Tampa PC Production",
#     "Tampa PC WHSE",
#     "Tampa PC Production",
#     "Tampa PC QA",
#     "Tampa PC QA",
#     "Tampa Transport",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Ft. Myers",
#     "Ft. Myers",
#     "Ft. Myers",
#     "Ft. Myers",
#     "Ft. Myers",
#     "Ft. Myers",
#     "Ft. Myers",
#     "Ft. Myers",
#     "Ft. Myers",
#     "Ft. Myers",
#     "Ft. Myers",
#     "Ft. Myers",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Ft. Myers",
#     "Ft. Myers",
#     "Ft. Myers",
#     "Ft. Myers",
#     "Ft. Myers",
#     "Ft. Myers",
#     "Ft. Myers",
#     "Ft. Myers",
#     "Ft. Myers",
#     "Ft. Myers",
#     "Ft. Myers",
#     "Ft. Myers",
#     "Ft. Myers",
#     "Ft. Myers",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Brevard",
#     "Brevard",
#     "Field Service",
#     "Field Service",
#     "Brevard",
#     "Brevard",
#     "Brevard",
#     "Brevard",
#     "Brevard",
#     "Brevard",
#     "Brevard",
#     "Brevard",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Daytona",
#     "Daytona",
#     "Daytona",
#     "Daytona",
#     "Daytona",
#     "Daytona",
#     "Daytona",
#     "Daytona",
#     "Daytona",
#     "Daytona",
#     "Daytona",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Daytona",
#     "Field Service",
#     "Field Service",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Field Service",
#     "Field Service",
#     "Field Service",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Gainesville",
#     "Gainesville",
#     "Gainesville",
#     "Gainesville",
#     "Gainesville",
#     "Gainesville",
#     "Gainesville",
#     "Gainesville",
#     "Gainesville",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Gainesville",
#     "Ocala ",
#     "Ocala ",
#     "Ocala ",
#     "Ocala ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Jacksonville ",
#     "Sebring",
#     "Sebring",
#     "Sebring",
#     "Sebring",
#     "Brevard",
#     "Brevard",
#     "Brevard",
#     "Brevard",
#     "Brevard",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Broward",
#     "Daytona",
#     "Daytona",
#     "Daytona",
#     "Daytona",
#     "Daytona",
#     "Daytona",
#     "Ft. Myers",
#     "Ft. Myers",
#     "Ft. Myers",
#     "Ft. Myers",
#     "Ft. Myers",
#     "Ft. Myers",
#     "Ft. Myers",
#     "Ft. Myers",
#     "Ft. Pierce",
#     "Ft. Pierce",
#     "Ft. Pierce",
#     "Ft. Pierce",
#     "Ft. Pierce",
#     "Ft. Pierce",
#     "Ft. Pierce",
#     "Ft. Pierce",
#     "Ft. Pierce",
#     "Ft. Pierce",
#     "Ft. Pierce",
#     "Ft. Pierce",
#     "Ft. Pierce",
#     "Ft. Pierce",
#     "Gainesville",
#     "Gainesville",
#     "Gainesville",
#     "Gainesville",
#     "Jacksonville",
#     "Jacksonville",
#     "Jacksonville",
#     "Jacksonville",
#     "Jacksonville",
#     "Jacksonville",
#     "Jacksonville",
#     "Jacksonville",
#     "Jacksonville",
#     "Jacksonville",
#     "Jacksonville",
#     "Jacksonville",
#     "Jacksonville",
#     "Jacksonville",
#     "Jacksonville",
#     "Jacksonville",
#     "Jacksonville",
#     "Winter Haven Sales",
#     "Winter Haven Sales",
#     "Winter Haven Sales",
#     "Winter Haven Sales",
#     "Winter Haven Sales",
#     "Winter Haven Sales",
#     "Ocala",
#     "Ocala",
#     "Ocala",
#     "Ocala",
#     "Ocala",
#     "Ocala",
#     "Ocala",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Orlando",
#     "Sarasota DIST",
#     "Sarasota DIST",
#     "Sarasota Sales",
#     "Sarasota Sales",
#     "Sarasota Sales",
#     "Sarasota Sales",
#     "Sarasota Sales",
#     "Sarasota Sales",
#     "Sebring",
#     "Sebring",
#     "Spring Hill Sales",
#     "Spring Hill Sales",
#     "Spring Hill Sales",
#     "Spring Hill Sales",
#     "St Petersburg Sales",
#     "St Petersburg Sales",
#     "St Petersburg Sales",
#     "St Petersburg Sales",
#     "Tampa DC Sales",
#     "Tampa DC DIST",
#     "Tampa DC Sales",
#     "Tampa DC DIST",
#     "Tampa DC DIST",
#     "Tampa DC DIST",
#     "Tampa DC DIST",
#     "Tampa DC WHSE",
#     "Tampa DC WHSE",
#     "Tampa PC MAINT",
#     "Tampa PC Production",
#     "Tampa PC Production",
#     "Tampa PC Production",
#     "Tampa PC Production",
#     "Tampa PC Production",
#     "Tampa PC Production",
#     "Tampa PC Production",
#     "Tampa DC Sales",
#     "Tampa DC Sales",
#     "Tampa DC Sales",
#     "Tampa DC Sales",
#     "Tampa DC Sales",
#     "Tampa DC Sales",
#     "Tampa DC Sales",
#     "Tampa DC Sales",
#     "Tampa Fleet",
#     "Tampa DC WHSE",
#     "Jacksonville",
#     "Broward",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "Ft. Myers",
#     "Ft. Myers",
#     "Ft. Myers",
#     "Ft. Myers",
#     "Ft. Myers",
#     "Ft. Pierce",
#     "Ft. Pierce",
#     "Ft. Pierce",
#     "Ft. Pierce",
#     "Ft. Pierce",
#     "Ft. Pierce",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "Miami-Dade",
#     "Miami-Dade",
#     "Miami-Dade",
#     "Miami-Dade",
#     "Miami-Dade",
#     "Miami-Dade",
#     "Miami-Dade",
#     "Miami-Dade",
#     "Miami-Dade",
#     "Miami-Dade",
#     "Miami-Dade",
#     "Miami-Dade",
#     "Miami-Dade",
#     "Miami-Dade",
#     "Miami-Dade",
#     "Miami-Dade",
#     "Miami-Dade",
#     "Miami-Dade",
#     "Miami-Dade",
#     "Miami-Dade",
#     "Miami-Dade",
#     "Miami-Dade",
#     "Miami-Dade",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "Orlando",
#     "Orlando",
#     "Palm Beach",
#     "Palm Beach",
#     "Palm Beach",
#     "Palm Beach",
#     "Palm Beach",
#     "Palm Beach",
#     "Palm Beach",
#     "Palm Beach",
#     "Palm Beach",
#     "Palm Beach",
#     "Palm Beach",
#     "Palm Beach",
#     "Palm Beach",
#     "Palm Beach",
#     "Palm Beach",
#     "Palm Beach",
#     "Palm Beach",
#     "Palm Beach",
#     "Palm Beach",
#     "Palm Beach",
#     "Palm Beach",
#     "Palm Beach",
#     "Palm Beach",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "Spring Hill Sales",
#     "St Petersburg Sales",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "PLACEHOLDER",
#     "The Keys",
#     "The Keys",
#     "The Keys",
#     "The Keys",
#     "PLACEHOLDER"
#
#   ),
#
#   Location = c(
#     "Fleet",
#     "Winter Haven Fleet",
#     "Tampa/Winter Haven/Ft Pierce Fleet",
#     "Tampa/Sarasota/Ft Myers Fleet",
#     "Winter Haven Distribution 1",
#     "Winter Haven Distribution 2",
#     "Winter Haven Distribution 3",
#     "Winter Haven Sales Team 1",
#     "Winter Haven Sales Team 2",
#     "Winter Haven Sales Team 3",
#     "Winter Haven Sales Merchandising Team 1",
#     "Winter Haven Sales Merchandising Team 2",
#     "Winter Haven Sales Merchandising Team 3",
#     "Winter Haven Sales Merchandising Team 4",
#     "Winter Haven Sales Merchandising Team 5",
#     "Winter Haven Warehouse 1",
#     "Winter Haven Warehouse 2",
#     "Winter Haven Warehouse 3",
#     "Winter Haven Territory",
#     "Winter Haven Logistics",
#     "Winter Haven Sales",
#     "Sarasota Distribution 1",
#     "Sarasota Distribution 2",
#     "Sarasota Administration",
#     "Sarasota Equipment Services",
#     "Sarasota Logistics",
#     "Sarasota Full Service",
#     "Sarasota Sales Merchandising Team 1",
#     "Sarasota Sales Merchandising Team 2",
#     "Sarasota Sales Merchandising Team 3",
#     "Sarasota Sales Merchandising Team 4",
#     "Sarasota Sales Merchandising Team 5",
#     "Sarasota Merchandising 1",
#     "Sarasota Sales",
#     "Sarasota Sales Team 1",
#     "Sarasota Sales Team 2",
#     # "Sarasota Sales Team 3",
#     "Sarasota Sales Team 4",
#     "Sarasota Territory",
#     "Sarasota Warehouse 1",
#     "Sarasota Warehouse 2",
#     "Springhill Distribution",
#     "Spring Hill Sales Merchandising Team 1",
#     "Spring Hill Sales Merchandising Team 2",
#     "Spring Hill Sales Merchandising Team 3",
#     "Spring Hill Sales Merchandising Team 4",
#     "Spring Hill Sales Team 1",
#     "Spring Hill Sales Team 2",
#     "Spring Hill Territory",
#     "St Petersburg Sales Merchandising Team 1",
#     "St Petersburg Sales Merchandising Team 2",
#     "St Petersburg Sales Merchandising Team 3",
#     "St Petersburg Sales Merchandising Team 4",
#     "St Petersburg Sales Merchandising Team 5",
#     "St Petersburg Sales Merchandising Team 6",
#     "St Petersburg Sales",
#     "St Petersburg Sales Team 1",
#     "St Petersburg Sales Team 2",
#     "St Petersburg Sales Team 3",
#     "St Petersburg Sales Team 4",
#     "Reset Sales Team 4",
#     "Tampa Distribution",
#     "Tampa Distribution 1",
#     "Tampa Distribution 2",
#     "Tampa Distribution 3",
#     "Tampa Distribution 4",
#     "Tampa Distribution 5",
#     "Tampa Distribution 6",
#     "Tampa Full Service 1",
#     "Tampa Full Service 2",
#     "Tampa Inventory",
#     "Tampa Logistics",
#     "Tampa Sales",
#     "Tampa Sales 1",
#     "Tampa Sales 2",
#     "Tampa Sales 3",
#     "Tampa Sales 4",
#     "Tampa Sales 5",
#     "Tampa Sales Merchandising 1",
#     "Tampa Sales Merchandising 2",
#     "Tampa Sales Merchandising 3",
#     "Tampa Sales Merchandising 4",
#     "Tampa Sales Merchandising 5",
#     "Tampa Sales Merchandising 6",
#     "Tampa Sales Merchandising 7",
#     "Tampa Sales Team",
#     "Tampa Territory",
#     "Tampa Warehouse",
#     "Tampa Warehouse 1",
#     "Tampa Warehouse 2",
#     "Tampa Warehouse 3",
#     "Tampa Warehouse 4",
#     "Tampa Warehouse 5",
#     "Tampa Warehouse 6",
#     "Tampa Warehouse 7",
#     "Tampa Warehouse 8",
#     "Tampa Equipment Svc Planned Bottle/Can",
#     "Tampa Equipment Svc Planned Fountain",
#     "Equipment Services",
#     "Tampa Equipment Services 1",
#     "Tampa Equipment Services 2",
#     "Tampa Production Team 1",
#     "Tampa Production Team 2",
#     "Tampa Production Team 3",
#     "Tampa Production Team 4",
#     "Tampa Production Team 5",
#     "Tampa Production Team 6",
#     "Tampa Warehouse Team 1",
#     "Tampa Warehouse Team 2",
#     "Tampa Warehouse Team 3",
#     "Tampa Maintenance Team 1",
#     "Tampa Maintenance Team 2",
#     "Tampa Maintenance",
#     "Tampa Production Center",
#     "Tampa Inventory Control",
#     "Tampa Operations",
#     "Tampa Quality Assurance",
#     "Tampa Quality Assurance Team",
#     "Florida Private Fleet",
#     "Hollywood Warehouse Team 8",
#     "Hollywood Warehouse Team 8",
#     "Hollywood Warehouse Team 3",
#     "Hollywood Warehouse Team 9",
#     "Hollywood Warehouse Team 5",
#     "Hollywood Warehouse Team 2",
#     "Broward Sales Merchandising Team 13",
#     "Broward Sales Merchandising Team 4",
#     "Hollywood Warehouse Team 6",
#     "Hollywood Warehouse Team 1A",
#     "Broward Sales Merchandising Team 10",
#     "Hollywood Distribution Bulk Team 2",
#     "Hollywood Production 9",
#     "Hollywood Production 4",
#     "Hollywood Distribution",
#     "Commercial Operations - South",
#     "Hollywood Distribution OFS Team 3",
#     "Hollywood Distribution Bulk Team 3",
#     "Talent and Learning",
#     "Hollywood Distribution OFS Team 2",
#     "Broward Sales Merchandising Team 7",
#     "Management Systems Team - Hollywood FL",
#     "Broward Territory",
#     "Broward Sales Merchandising Team 5",
#     "Hollywood Production 6",
#     "Hollywood Distribution OFS Team 4",
#     "Hollywood Distribution OFS Team 1",
#     "Hollywood Production 7",
#     "Hollywood Production 3",
#     "Hollywood Maintenance Team 3",
#     "Broward Inventory",
#     "Broward Sales 7",
#     "Broward Sales",
#     "Broward Sales Merchandising Team 2",
#     "Broward Sales Merchandising Team 9",
#     "Hollywood Equipment Services Team I",
#     "Hollywood Equipment Service Team III",
#     "Finance Services Team 1",
#     "Hollywood Production 1",
#     "Hollywood Production Sanitation",
#     "Broward Inventory Team 1",
#     "Hollywood Cooler Mover Team",
#     "Broward Sales Merchandising Team 1",
#     "Hollywood Production 8",
#     "Hollywood Quality Control Team 3",
#     "Florida Division Fleet - Hollywood",
#     "Broward Sales Merchandising Team 11",
#     "Hollywood Warehouse Team 3A",
#     "Hollywood Warehouse Team 6A",
#     "Hollywood Equipment Services Team 2",
#     "Hollywood Warehouse Team 2A",
#     "Hollywood Production 10",
#     "Broward Sales Merchandising Team 12",
#     "Broward Business Development Team",
#     "Broward Sales 1",
#     "Broward Sales Merchandising Team 8",
#     "Broward Sales Team 1",
#     "Broward Sales 4",
#     "Broward Sales 8",
#     "Broward Sales 5",
#     "Reset Sales Team 3",
#     "Environmental Health Safety & Sustain",
#     "Broward Sales Merchandising Team 3",
#     "Hollywood Maintenance Team 1",
#     "Broward Logistics",
#     "Hollywood Distribution OFS Team 5",
#     "Broward Sales Merchandising Team 6",
#     "Broward Sales 3",
#     "Hollywood Full Service",
#     "Hollywood Warehouse Team 4",
#     "Hollywood Quality Control Team 2",
#     "Small Store Customer Management",
#     "Hollywood Distribution Bulk Team 1",
#     "Hollywood Quality Control Team 1",
#     "Hollywood Warehouse Team 4A",
#     "Hollywood Maintenance Team 4",
#     "US Region Field Ops - Field Svc MU Lead",
#     "Hollywood Production",
#     "Finance Services Team 3",
#     "Hollywood Warehouse Team 1",
#     "Hollywood Warehouse Team 7",
#     "Hollywood Maintenance",
#     "Broward Sales 2",
#     "Broward Sales Team 2",
#     "Regional and Local Accounts Customer Mgt",
#     "Security",
#     "Broward Warehouse Team",
#     "Director Field IT",
#     "FSOP Customer Management (South)",
#     "Hollywood Quality Assurance",
#     "Hollywood Production Center",
#     "Public Affairs and Community Relations",
#     "Hollywood Maintenance Team 2",
#     "Corporate HR & Ops",
#     "Hollywood Warehouse",
#     "Manager, Internal Control",
#     "Fort Myers Warehouse 2",
#     "Fort Myers Warehouse 1",
#     "Ft Myers Equipment Services",
#     "Fort Myers Territory",
#     "Fort Myers Logistics",
#     "Fort Myers Distribution 2",
#     "Fort Myers Distribution 1",
#     "Fort Myers Distribution 4",
#     "Fort Myers Distribution 3",
#     "Fort Myers Warehouse 3",
#     "Ft Myers Sales",
#     "Fort Myers Warehouse",
#     "Broward Distribution",
#     "Broward Distribution Team 1",
#     "Broward Distribution Team 2",
#     "Broward Distribution Team 3",
#     "Broward Distribution Team 4",
#     "Broward Distribution Team 5",
#     "Broward Distribution Team 6",
#     "Broward Distribution Team 7",
#     "Broward Distribution Team 8",
#     "Broward Distribution Team 9",
#     "Broward Field Service Team 1",
#     "Broward Field Service Team 2",
#     "Broward Field Service Team 3",
#     "Broward Maintenance",
#     "Broward Maintenance Team 1",
#     "Broward Maintenance Team 3",
#     "Broward Maintenance Team 4",
#     "Broward Management Systems Team",
#     "Broward Production",
#     "Broward Production 1",
#     "Broward Production 10",
#     "Broward Production 3",
#     "Broward Production 4",
#     "Broward Production 6",
#     "Broward Production 7",
#     "Broward Production 8",
#     "Broward Production 9",
#     "Broward Production Warehouse 1",
#     "Broward Production Warehouse 2",
#     "Broward Production Warehouse 3",
#     "Broward Production Warehouse 4",
#     "Broward Production Warehouse 6",
#     "Broward Warehouse Team 1",
#     "Broward Warehouse Team 2",
#     "Broward/The Keys Fleet",
#     "Field IT",
#     "Field Service Team 3",
#     "Internal Control",
#     "Ft Myers Business Development Team",
#     "Ft Myers Field Service",
#     "Ft Myers Sales Merchandising Team 1",
#     "Ft Myers Sales Merchandising Team 2",
#     "Ft Myers Sales Merchandising Team 3",
#     "Ft Myers Sales Merchandising Team 4",
#     "Ft Myers Sales Merchandising Team 5",
#     "Ft Myers Sales Merchandising Team 6",
#     "Ft Myers Sales Merchandising Team 7",
#     "Ft Myers Sales Merchandising Team 8",
#     "Ft Myers Sales Team 1",
#     "Ft Myers Sales Team 2",
#     "Ft Myers Sales Team 3",
#     "Ft Myers Sales Team 4",
#     "Broward Quality Assurance",
#     "Broward Quality Assurance 1",
#     "Broward Quality Assurance 2",
#     "Broward Quality Assurance 3",
#     "Broward Warehouse 3",
#     "Broward Warehouse 4",
#     "Broward Warehouse 5",
#     "Broward Warehouse 6",
#     "Brevard Distribution Team 1",
#     "Brevard Distribution Team 2",
#     "Brevard Field Service",
#     "Brevard Full Service",
#     "Brevard Sales Merchandising Team 1",
#     "Brevard Sales Merchandising Team 2",
#     "Brevard Sales Merchandising Team 3",
#     "Brevard Sales Merchandising Team 4",
#     "Brevard Sales Team 1",
#     "Brevard Sales Team 2",
#     "Brevard Territory",
#     "Business Services and Systems",
#     "Channel Marketing",
#     "Commercial Capabilities",
#     "Corporate HR & Ops",
#     "Customer Management ï¿½ FSOP",    # NOTE the weird one is here and right below
#     "Customer Management ï¿½ Retail",
#     "Daytona Distribution",
#     "Daytona Distribution Team 1",
#     "Daytona Distribution Team 2",
#     "Daytona Sales Merchandising Team 1",
#     "Daytona Sales Merchandising Team 2",
#     "Daytona Sales Merchandising Team 3",
#     "Daytona Sales Merchandising Team 4",
#     "Daytona Sales Team 1",
#     "Daytona Sales Team 2",
#     "Daytona Sales Team 3",
#     "Daytona Territory",
#     "Environmental Health Safety & Sustain",
#     "Field IT",
#     "Finance Services Team 2",
#     "Finance Services Team 3",
#     "Jacksonville/Daytona Field Service Team",
#     "Make Ready Center",
#     "MRC & Field Service",
#     "Ocala Sales Merchandising Team 4",
#     "Orlando Business Development Team",
#     "Orlando Distribution",
#     "Orlando Distribution Center",
#     "Orlando Distribution Team 1",
#     "Orlando Distribution Team 2",
#     "Orlando Distribution Team 3",
#     "Orlando Distribution Team 4",
#     "Orlando Distribution Team 5",
#     "Orlando Distribution Team 6",
#     "Orlando Distribution Team 7",
#     "Orlando Field Service Team 1",
#     "Orlando Field Service Team 2",
#     "Orlando Field Service Team 3",
#     "Orlando Full Service 1",
#     "Orlando Full Service 2",
#     "Orlando Inventory Control",
#     "Orlando Maintenance",
#     "Orlando Maintenance Team 1",
#     "Orlando Maintenance Team 2",
#     "Orlando Management Systems",
#     "Orlando Manufacturing",
#     "Orlando Production",
#     "Orlando Production Team 1",
#     "Orlando Production Team 2",
#     "Orlando Production Team 3",
#     "Orlando Production Team 4",
#     "Orlando Production Team 5",
#     "Orlando Production Team 6",
#     "Orlando Quality Assurance",
#     "Orlando Quality Assurance 1",
#     "Orlando Quality Assurance 2",
#     "Orlando Sales",
#     "Orlando Sales 1",
#     "Orlando Sales 10",
#     "Orlando Sales 2",
#     "Orlando Sales 3",
#     "Orlando Sales 4",
#     "Orlando Sales 5",
#     "Orlando Sales 6",
#     "Orlando Sales 7",
#     "Orlando Sales 9",
#     "Orlando Sales Merchandising Team 1",
#     "Orlando Sales Merchandising Team 10",
#     "Orlando Sales Merchandising Team 11",
#     "Orlando Sales Merchandising Team 12",
#     "Orlando Sales Merchandising Team 13",
#     "Orlando Sales Merchandising Team 2",
#     "Orlando Sales Merchandising Team 3",
#     "Orlando Sales Merchandising Team 4",
#     "Orlando Sales Merchandising Team 5",
#     "Orlando Sales Merchandising Team 6",
#     "Orlando Sales Merchandising Team 7",
#     "Orlando Sales Merchandising Team 8",
#     "Orlando Sales Merchandising Team 9",
#     "Orlando Sales Team",
#     "Orlando Territory",
#     "Orlando Transport",
#     "Orlando Warehouse Team 1",
#     "Orlando Warehouse Team 10",
#     "Orlando Warehouse Team 11",
#     "Orlando Warehouse Team 2",
#     "Orlando Warehouse Team 2A",
#     "Orlando Warehouse Team 3",
#     "Orlando Warehouse Team 3A",
#     "Orlando Warehouse Team 4",
#     "Orlando Warehouse Team 5",
#     "Orlando Warehouse Team 6",
#     "Orlando Warehouse Team 7",
#     "Orlando Warehouse Team 8",
#     "Orlando Warehouse Transportation",
#     "Orlando/Brevard Fleet",
#     "Reset Sales Team 1",
#     "Reset Sales Team 2",
#     "Talent and Learning",
#     "Business Services and Systems",
#     "Channel Marketing",
#     "Corporate HR & Ops",
#     "Engineering",
#     "Environmental Health Safety & Sustain",
#     "Field IT",
#     "Field Service Team 2",
#     "Finance Services Team 2",
#     "FSOP Customer Management (South)",
#     "Gainesville Distribution Team 1",
#     "Gainesville Distribution Team 2",
#     "Gainesville Distribution Team 3",
#     "Gainesville Merchandising Team 1",
#     "Gainesville Merchandising Team 2",
#     "Gainesville Merchandising Team 3",
#     "Gainesville Sales Team 1",
#     "Gainesville Sales Team 2",
#     "Gainesville Territory",
#     "Jacksonville Business Development Team",
#     "Jacksonville Distribution",
#     "Jacksonville Distribution Team 1",
#     "Jacksonville Distribution Team 2",
#     "Jacksonville Distribution Team 3",
#     "Jacksonville Distribution Team 4",
#     "Jacksonville Distribution Team 5",
#     "Jacksonville Field Service Team 1",
#     "Jacksonville Full Service",
#     "Jacksonville Inventory",
#     "Jacksonville Inventory Team 1",
#     "Jacksonville Inventory Team 2",
#     "Jacksonville Inventory Team 3",
#     "Jacksonville Logistics",
#     "Jacksonville Maintenance",
#     "Jacksonville Maintenance Team 1",
#     "Jacksonville Maintenance Team 2",
#     "Jacksonville Manufacturing",
#     "Jacksonville Merchandising Team 1",
#     "Jacksonville Merchandising Team 10",
#     "Jacksonville Merchandising Team 2",
#     "Jacksonville Merchandising Team 3",
#     "Jacksonville Merchandising Team 4",
#     "Jacksonville Merchandising Team 5",
#     "Jacksonville Merchandising Team 6",
#     "Jacksonville Merchandising Team 7",
#     "Jacksonville Merchandising Team 8",
#     "Jacksonville Merchandising Team 9",
#     "Jacksonville Production",
#     "Jacksonville Production Team 2",
#     "Jacksonville Production Team 2",
#     "Jacksonville Production Team 3",
#     "Jacksonville Production Team 4",
#     "Jacksonville Production Team 5",
#     "Jacksonville Quality Assurance",
#     "Jacksonville Quality Assurance Team 1",
#     "Jacksonville Sales",
#     "Jacksonville Sales 1",
#     "Jacksonville Sales 2",
#     "Jacksonville Sales 3",
#     "Jacksonville Sales 5",
#     "Jacksonville Sales 6",
#     "Jacksonville Sales Team 1",
#     "Jacksonville Sales Team 2",
#     "Jacksonville Territory",
#     "Jacksonville Transportation",
#     "Jacksonville Warehouse Team 1",
#     "Jacksonville Warehouse Team 2",
#     "Jacksonville Warehouse Team 3",
#     "Jacksonville Warehouse Team 4",
#     "Jacksonville Warehouse Team 5",
#     "Jacksonville Warehouse Team 6",
#     "Jacksonville Warehouse Team 7",
#     "Jacksonville/Daytona Field Service Team",
#     "Jacksonville/Gainesville Fleet",
#     "Jax/Gainesville Field Service Team",
#     "Ocala Merchandising Team 3",
#     "Ocala Sales Merchandising Team 1",
#     "Ocala Sales Merchandising Team 4",
#     "Ocala Territory",
#     "Regional and Local Accounts Customer Mgt",
#     "Reset Sales Team 2",
#     "Security",
#     "Talent and Learning",
#     "Technology Solutions Team 1",
#     "Sebring Sales Merchandising Team 1",
#     "Sebring Sales Merchandising Team 2",
#     "Sebring Sales Team 1",
#     "Sebring Territory",
#     "Brevard Distribution Administration",
#     "Brevard Full Service Team",
#     "Brevard Sales Team 1 Admin",
#     "Brevard Sales Team 2 Admin",
#     "Brevard Territory Admin",
#     "Broward Distribution Admin",
#     "Broward Inventory Admin",
#     "Broward Logistics Admin",
#     "Broward Maintenance Admin",
#     "Broward Maintenance Team 2",
#     "Broward Production Admin",
#     "Broward Production Center Admin",
#     "Broward Production Warehouse 5",
#     "Broward Sales 1 Admin",
#     "Broward Sales 2 Admin",
#     "Broward Sales 3 Admin",
#     "Broward Sales 4 Admin",
#     "Broward Sales 5 Admin",
#     "Broward Sales 6 Admin",
#     "Broward Sales 7 Admin",
#     "Broward Sales 8 Admin",
#     "Broward Sales Admin",
#     "Broward Sales Team 2 Admin",
#     "Broward Territory Admin",
#     "Broward Warehouse 1",
#     "Broward Warehouse 2",
#     "Broward Warehouse 7",
#     "Broward Warehouse 8",
#     "Broward Warehouse 9",
#     "Broward Warehouse Team 1 Admin",
#     "Broward Warehouse Team 2 Admin",
#     "Daytona Distribution Admin",
#     "Daytona Distribution Team 3",
#     "Daytona Sales Team 1 Admin",
#     "Daytona Sales Team 2 Admin",
#     "Daytona Sales Team 3 Admin",
#     "Daytona Territory Admin",
#     "Fort Myers Logistics Admin",
#     "Fort Myers Territory Admin",
#     "Fort Myers Warehouse Admin",
#     "Fort Myers Sales Admin",
#     "Fort Myers Sales Team 1 Admin",
#     "Fort Myers Sales Team 2 Admin",
#     "Fort Myers Sales Team 3 Admin",
#     "Fort Myers Sales Team 4 Admin",
#     "Ft Pierce Distribution 1",
#     "Ft Pierce Distribution 2",
#     "Ft Pierce Field Service",
#     "Ft Pierce Logistics Admin",
#     "Ft Pierce Sales Merchandising Team 1",
#     "Ft Pierce Sales Merchandising Team 2",
#     "Ft Pierce Sales Merchandising Team 3",
#     "Ft Pierce Sales Merchandising Team 4",
#     "Ft Pierce Sales Sales Team 1 Admin",
#     "Ft Pierce Sales Sales Team 2 Admin",
#     "Ft Pierce Sales Sales Team 3 Admin",
#     "Ft Pierce Sales Territory Admin",
#     "Ft Pierce Sales Warehouse 1",
#     "Ft Pierce Sales Warehouse 2",
#     "Gainesville Distribution Administration",
#     "Gainesville Sales Team 1 Admin",
#     "Gainesville Sales Team 2 Admin",
#     "Gainesville Territory Admin",
#     "Jacksonville Distribution Admin",
#     "Jacksonville Inventory Admin",
#     "Jacksonville Maintenance Admin",
#     "Jacksonville Manufacturing Admin",
#     "Jacksonville Production Admin",
#     "Jacksonville Quality Assurance Admin",
#     "Jacksonville Sales 1 Admin",
#     "Jacksonville Sales 2 Admin",
#     "Jacksonville Sales 3 Admin",
#     "Jacksonville Sales 4 Admin",
#     "Jacksonville Sales 5 Admin",
#     "Jacksonville Sales 6 Admin",
#     "Jacksonville Sales Admin",
#     "Jacksonville Sales Team 1 Admin",
#     "Jacksonville Sales Team 2 Admin",
#     "Jacksonville Territory Admin",
#     "Jacksonville/Gainesville Field Service Team",
#     "Winter Haven Logistics Admin",
#     "Winter Haven Sales Admin",
#     "Winter Haven Sales Team 1 Admin",
#     "Winter Haven Sales Team 2 Admin",
#     "Winter Haven Sales Team 3 Admin",
#     "Winter Haven Territory Admin",
#     "Ocala Sales Merchandising Team 2",
#     "Ocala Sales Merchandising Team 3",
#     "Ocala Sales Merchandising Team 5",
#     "Ocala Sales Team 1 Admin",
#     "Ocala Sales Team 2 Admin",
#     "Ocala Sales Team 3 Admin",
#     "Ocala Territory Admin",
#     "Orlando Distribution Admin",
#     "Orlando Distribution Center Admin",
#     "Orlando Maintenance Admin",
#     "Orlando Manufacturing Admin",
#     "Orlando Production Admin",
#     "Orlando Quality Assurance Admin",
#     "Orlando Sales 1 Admin",
#     "Orlando Sales 10 Admin",
#     "Orlando Sales 2 Admin",
#     "Orlando Sales 3 Admin",
#     "Orlando Sales 4 Admin",
#     "Orlando Sales 5 Admin",
#     "Orlando Sales 6 Admin",
#     "Orlando Sales 7 Admin",
#     "Orlando Sales 8 Admin",
#     "Orlando Sales 9 Admin",
#     "Orlando Sales Admin",
#     "Orlando Territory Admin",
#     "Orlando Transport Admin",
#     "Orlando Warehouse Team 4A Admin",
#     "Orlando Warehouse Transportation Admin",
#     "Sarasota Field Service",
#     "Sarasota Logistics Admin",
#     "Sarasota Sales Admin",
#     "Sarasota Sales Team 1 Admin",
#     "Sarasota Sales Team 2 Admin",
#     "Sarasota Sales Team 3 Admin",
#     "Sarasota Sales Team 4 Admin",
#     "Sarasota Territory Admin",
#     "Sebring Sales Team 1 Admin",
#     "Sebring Territory Admin",
#     "Spring Hill Sales Team 1 Admin",
#     "Spring Hill Sales Team 2 Admin",
#     "Spring Hill Territory Admin",
#     "Springhill Distribution Team",
#     "St Petersburg Sales Team 1 Admin",
#     "St Petersburg Sales Team 2 Admin",
#     "St Petersburg Sales Team 3 Admin",
#     "St Petersburg Sales Team 4 Admin",
#     "Tampa Business Development Team",
#     "Tampa Distribution Admin",
#     "Tampa Business Development Team",
#     "Tampa Field Service Team 1",
#     "Tampa Field Service Team 2",
#     "Tampa Field Service Team 3",
#     "Tampa Field Service Team 4",
#     "Tampa Inventory Control Admin",
#     "Tampa Logistics Admin",
#     "Tampa Maintenance Admin",
#     "Tampa Production Center Admin",
#     "Tampa Production Admin",
#     "Tampa Production Warehouse Team 1",
#     "Tampa Production Warehouse Team 2",
#     "Tampa Production Warehouse Team 3",
#     "Tampa Quality Assurance Admin",
#     "Tampa Quality Assurance Team 1",
#     "Tampa Sales 1 Admin",
#     "Tampa Sales 2 Admin",
#     "Tampa Sales 3 Admin",
#     "Tampa Sales 4 Admin",
#     "Tampa Sales 5 Admin",
#     "Tampa Sales Admin",
#     "Tampa Sales Team Admin",
#     "Tampa Territory Admin",
#     "Tampa Transportation Team 1",
#     "Tampa Warehouse Admin",
#     "Technology Solutions Team 2",
#     "Broward Quality Assurance Admin",
#     "Business Development Administration",
#     "Business Services and Systems Administration",
#     "Centralized Finance Services Admin",
#     "Channel Marketing Admin",
#     "Coke Florida Admin",
#     "Commercial Capabilities Admin",
#     "Commercial Capabilities Team 1",
#     "Commercial Capabilities Team 2",
#     "Commercial Operations FSOP",
#     "Communications Team",
#     "Consumer Insights and Comm Solutions Admin",
#     "Content Creation",
#     "Controller Admin",
#     "Corp Development and Gov Relations Admin",
#     "Corporate HR and Ops Team",
#     "Cost Accounting Team",
#     "Customer Management - Walmart",
#     "Customer Management FSOP",
#     "Customer Management Retail",
#     "Demand Forecast and Operations Planning Admin",
#     "Demand Planning Team",
#     "Distribution Operations Admin",
#     "Engineering Team",
#     "Environmental Health Safety and Sustain Admin",
#     "Field IT Admin",
#     "Field Logistics Planning Admin",
#     "Field Planning 1",
#     "Field Planning 2",
#     "Field Planning 3",
#     "Field Service Team 1 Admin",
#     "Field Service Team 2 Admin",
#     "Field Service Team 3 Admin",
#     "Finance Admin",
#     "Finance Planning Team",
#     "Fleet Admin",
#     "Franchise Field Operations Admin",
#     "FSOP Customer Management (North)",
#     "Ft Myers Sales Admin",
#     "Ft Myers Sales Team 1 Admin",
#     "Ft Myers Sales Team 2 Admin",
#     "Ft Myers Sales Team 3 Admin",
#     "Ft Myers Sales Team 4 Admin",
#     "Ft Pierce Sales Team 1 Admin",
#     "Ft Pierce Sales Team 2 Admin",
#     "Ft Pierce Sales Team 3 Admin",
#     "Ft Pierce Territory Admin",
#     "Ft Pierce Warehouse 1",
#     "Ft Pierce Warehouse 2",
#     "GTM and Insights Team",
#     "Headquarter Office - Cardinal Management Services Administration",
#     "Human Resources",
#     "Internal Control Team",
#     "IT and Enterprise Transformation Admin",
#     "Large Store Customer Management",
#     "Legal Team",
#     "Make Ready Center Team",
#     "Marketing Admin",
#     "Miami-Dade/Palm Beach Fleet",
#     "Miami Dade Distribution Team 2",
#     "Miami Dade Field Service",
#     "Miami Dade Logistics Admin",
#     "Miami Dade Sales Admin",
#     "Miami Dade Sales Merchandising Team 1",
#     "Miami Dade Sales Merchandising Team 2",
#     "Miami Dade Sales Merchandising Team 3",
#     "Miami Dade Sales Merchandising Team 4",
#     "Miami Dade Sales Merchandising Team 5",
#     "Miami Dade Sales Merchandising Team 6",
#     "Miami Dade Sales Merchandising Team 7",
#     "Miami Dade Sales Merchandising Team 8",
#     "Miami Dade Sales Merchandising Team 9",
#     "Miami Dade Sales Team 1 Admin",
#     "Miami Dade Sales Team 2 Admin",
#     "Miami Dade Sales Team 3 Admin",
#     "Miami Dade Sales Team 4 Admin",
#     "Miami Dade Sales Team 5 Admin",
#     "Miami Dade Sales Team 6 Admin",
#     "Miami Dade Territory Admin",
#     "Miami Dade Warehouse Team 1",
#     "Miami Dade Warehouse Team 2",
#     "MRC and Field Service Admin",
#     "Off-Invoice Pricing",
#     "Operations Planning Team",
#     "Orlando Management Systems Team",
#     "Orlando Transport Team",
#     "Orlando Warehouse Team 4A",
#     "Palm Beach Business Development Team",
#     "Palm Beach Distribution Team 1",
#     "Palm Beach Distribution Team 2",
#     "Palm Beach Distribution Team 3",
#     "Palm Beach Field Service Team 1",
#     "Palm Beach Field Service Team 2",
#     "Palm Beach Full Service",
#     "Palm Beach Logistics Admin",
#     "Palm Beach Sales Admin",
#     "Palm Beach Sales Merchandising Team 1",
#     "Palm Beach Sales Merchandising Team 2",
#     "Palm Beach Sales Merchandising Team 3",
#     "Palm Beach Sales Merchandising Team 4",
#     "Palm Beach Sales Merchandising Team 5",
#     "Palm Beach Sales Merchandising Team 6",
#     "Palm Beach Sales Merchandising Team 7",
#     "Palm Beach Sales Team 1 Admin",
#     "Palm Beach Sales Team 2 Admin",
#     "Palm Beach Sales Team 3 Admin",
#     "Palm Beach Sales Team 4 Admin",
#     "Palm Beach Territory Admin",
#     "Palm Beach Warehouse Team 2",
#     "Palm Beach Warehouse Team 3",
#     "PGM and Planning Admin",
#     "Planning Bottler/Production Team",
#     "Planning Commercial Lifecycle Team",
#     "Pricing Execution",
#     "Print Shop Team",
#     "Procurement Team",
#     "Product Supply Network Admin",
#     "Profit Growth and Analysis Team",
#     "Profit Growth Management Admin",
#     "Quality Admin",
#     "Recruitment Team",
#     "Regional and Local Accounts Customer Mgt Team",
#     "Risk Management",
#     "SAP Master Data Team",
#     "Security Admin",
#     "South Dade Warehouse Team 2",
#     "Springhill Distribution Team",
#     "St Petersburg Sales Admin",
#     "Strategy and Planning Admin",
#     "Supply Chain Planning Team",
#     "Talent Acquisition Admin",
#     "Talent and Learning Team",
#     "Territory North Admin",
#     "Territory South Admin",
#     "The Keys Distribution",
#     "The Keys Sales Team 1",
#     "The Keys Sales Team 2",
#     "The Keys Territory Admin",
#     "Total Rewards Team"
#
#
#   )
# )

# lms.locations <- lms.locations %>%
#   mutate(Location = recode(Location,
#                            "Customer Management Ã¯Â¿Â½ FSOP" = "Customer Management ï¿½ FSOP",
#                            "Customer Management Ã¯Â¿Â½ Retail" = "Customer Management ï¿½ Retail"))

# STARS ----

stars.locations <- data.frame( Location = c("FT MYERS",
                                            "TAMPA DC",
                                            "ORLANDO COMBO CENTER",
                                            "SARASOTA",
                                            "TAMPA (SABAL)",
                                            "DAYTONA DC",
                                            "JACKSONVILLE COMBO CENTER",
                                            "GAINESVILLE DC",
                                            "FORT PIERCE",
                                            "BREVARD DC",
                                            "TAMPA HQ",
                                            "ORLANDO MRC",
                                            "WINTER HAVEN",
                                            "COCA-COLA BEVERAGES FLORIDA, LLC",
                                            "JACKSONVILLE SURGE",
                                            "SEBRING",
                                            "BROWARD",
                                            "MIAMI DADE",
                                            "PALM BEACH",
                                            "THE KEYS"),
                               manager = c("TAMPA",
                                           "TAMPA",
                                           "ORLANDO",
                                           "TAMPA",
                                           "TAMPA",
                                           "JACKSONVILLE",
                                           "JACKSONVILLE",
                                           "JACKSONVILLE",
                                           "ORLANDO",
                                           "JACKSONVILLE",
                                           "PLACEHOLDER",
                                           "ORLANDO",
                                           "ORLANDO",
                                           "PLACEHOLDER",
                                           "JACKSONVILLE",
                                           "ORLANDO",
                                           "BROWARD",
                                           "BROWARD",
                                           "BROWARD",
                                           "BROWARD")
                               )

stars.locations$Location <- as.character(stars.locations$Location)


cbcs.years <- data.frame(year = c((as.numeric(format(Sys.Date(), "%Y")) - 1), (format(Sys.Date(), "%Y"))),
                    manager = c("TAMPA", "TAMPA", "ORLANDO", "ORLANDO", "BROWARD", "BROWARD", "JACKSONVILLE", "JACKSONVILLE"))

cbcs.cat <- data.frame(year = c((as.numeric(format(Sys.Date(), "%Y")) - 1), (format(Sys.Date(), "%Y"))),
                       Coverage = c("AUTO", "GL", "WC", "AUTO", "GL", "WC"))

typology.cost <- data.frame(
  col_keys = c(
    "Location",
    paste(as.numeric(format(Sys.Date(), '%Y')) - 1, "AUTO", sep = " "),
    paste(as.numeric(format(Sys.Date(), "%Y")), "AUTO", sep = " "),
    paste(as.numeric(format(Sys.Date(), '%Y')) - 1, "GL", sep = " "),
    paste(as.numeric(format(Sys.Date(), "%Y")), "GL", sep = " "),
    paste(as.numeric(format(Sys.Date(), '%Y')) - 1, "WC", sep = " "),
    paste(as.numeric(format(Sys.Date(), "%Y")), "WC",  sep = " "),
    paste(as.numeric(format(Sys.Date(), '%Y')) - 1, "Total", sep = " "),
    paste(as.numeric(format(Sys.Date(), "%Y")), "Total", sep = " "),
    "Fav/Unfav"
  ),

  what = c(
    "Claim Cost v LYR",
    "Auto",
    "Auto",
    "GL",
    "GL",
    "WC",
    "WC",
    "Total",
    "Total",
    "Diff"
  ),

  measure = c(
    "Location",
    as.numeric(format(Sys.Date(), "%Y")) - 1,
    as.numeric(format(Sys.Date(), "%Y")),
    as.numeric(format(Sys.Date(), "%Y")) - 1,
    as.numeric(format(Sys.Date(), "%Y")),
    as.numeric(format(Sys.Date(), "%Y")) - 1,
    as.numeric(format(Sys.Date(), "%Y")),
    as.numeric(format(Sys.Date(), "%Y")) - 1,
    as.numeric(format(Sys.Date(), "%Y")),
    "Fav/Unfav"
  ),

  stringsAsFactors = FALSE )

typology.count <- data.frame(
  col_keys = c(
    "Location",
    paste(as.numeric(format(Sys.Date(), '%Y')) - 1, "AUTO", sep = " "),
    paste(as.numeric(format(Sys.Date(), "%Y")), "AUTO", sep = " "),
    paste(as.numeric(format(Sys.Date(), '%Y')) - 1, "GL", sep = " "),
    paste(as.numeric(format(Sys.Date(), "%Y")), "GL", sep = " "),
    paste(as.numeric(format(Sys.Date(), '%Y')) - 1, "WC", sep = " "),
    paste(as.numeric(format(Sys.Date(), "%Y")), "WC",  sep = " "),
    paste(as.numeric(format(Sys.Date(), '%Y')) - 1, "Total", sep = " "),
    paste(as.numeric(format(Sys.Date(), "%Y")), "Total", sep = " "),
    "Fav/Unfav"
  ),

  what = c(
    "Claim Count v LYR",
    "AUTO",
    "AUTO",
    "GL",
    "GL",
    "WC",
    "WC",
    "Total",
    "Total",
    "Diff"
  ),

  measure = c(
    "Location",
    as.numeric(format(Sys.Date(), "%Y")) - 1,
    as.numeric(format(Sys.Date(), "%Y")),
    as.numeric(format(Sys.Date(), "%Y")) - 1,
    as.numeric(format(Sys.Date(), "%Y")),
    as.numeric(format(Sys.Date(), "%Y")) - 1,
    as.numeric(format(Sys.Date(), "%Y")),
    as.numeric(format(Sys.Date(), "%Y")) - 1,
    as.numeric(format(Sys.Date(), "%Y")),
    "Fav/Unfav"
  ),

  stringsAsFactors = FALSE )

cbcs.pivot.cat <- data.frame(year = c((as.numeric(format(Sys.Date(), "%Y")) - 1), (format(Sys.Date(), "%Y"))),
                       Coverage = c("AUTO", "GL", "WC", "AUTO", "GL", "WC"))
